# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-08 10:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Practical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('branch', models.IntegerField(choices=[(1, 'Computer Engineering'), (2, 'Mechanical Engineering'), (3, 'Electrical Engineering'), (4, 'Information Technology'), (5, 'EXTC')])),
                ('semester', models.IntegerField()),
                ('roll_no', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=128)),
                ('abbr', models.CharField(max_length=30)),
                ('sub_type', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SubjectHolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('branch', models.IntegerField(choices=[(1, 'Computer Engineering'), (2, 'Mechanical Engineering'), (3, 'Electrical Engineering'), (4, 'Information Technology'), (5, 'EXTC')])),
                ('semester', models.IntegerField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='attendence.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subs', to='attendence.Attendance')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendence.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='Theory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual', models.IntegerField()),
                ('total', models.IntegerField()),
                ('subject_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theory', to='attendence.SubjectStudent')),
            ],
        ),
        migrations.AddField(
            model_name='practical',
            name='subject_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practical', to='attendence.SubjectStudent'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='attendence.Student'),
        ),
    ]
