# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-08 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='batch_no',
        ),
        migrations.AddField(
            model_name='attendance',
            name='batch_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
