# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0003_subjectholder'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectholder',
            name='cols',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
