# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0004_subjectholder_cols'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectholder',
            name='plectures',
            field=models.IntegerField(default=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjectholder',
            name='tlectures',
            field=models.IntegerField(default=14),
            preserve_default=False,
        ),
    ]
