# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0005_auto_20170317_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='lecture_type',
            field=models.CharField(choices=[('TH', 'Theroy'), ('PR', 'Practicals'), ('TL', 'Total')], default='TH', max_length=2),
        ),
    ]
